functional-tests: remove java interoperability cases that fail to compile
Due to usage of jvm synthetic for members of
internal interfaces the interoperability cases
stopped to compile -- members of such interfaces
are not visible.

```
> Task :functional:compileReleaseUnitTestJavaWithJavac FAILED
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:34: error: method does not override or implement a method from a supertype
  @Override
  ^
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:39: error: method does not override or implement a method from a supertype
  @Override
```

Signed-off-by: Patryk Wrobel <183546751+pwrobeldev@users.noreply.github.com>