functional: showcase the interop problem with open class
When the collection holds the open class the
interoperability problems occur. The Kotlin
compiler assumes that the collection type
holds '? extends SomeClass'. The following
error was reproduced in tests.

```
> Task :functional:compileReleaseUnitTestJavaWithJavac FAILED
functional/android/src/test/java/com/here/android/test/KotlinInteropTest.java:42: error:
incompatible types: List<CAP#1> cannot be converted to List<SomeOpenNumberWrapperClass>
    assertEquals(0, someJavaFunctionThatTakesList(someStruct.openClassList));
                                                            ^
  where CAP#1 is a fresh type-variable:
    CAP#1 extends SomeOpenNumberWrapperClass from capture of ? extends SomeOpenNumberWrapperClass
```

Signed-off-by: Patryk Wrobel <183546751+pwrobeldev@users.noreply.github.com>