functional-tests: remove java interoperability cases that fail to compile
The previous changes ensure that more elements are not accessible in Java.
The following errors were visible -- the test cases were removed, because
with the new handling of nested internal the compilation error was expected.

```
> Task :functional:compileReleaseUnitTestJavaWithJavac FAILED
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:57: error: cannot find symbol
    SomeInternalClassWithMembers someObject = SomeInternalClassWithMembers.create();
                                                                          ^
  symbol:   method create()
  location: class SomeInternalClassWithMembers
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:58: error: cannot find symbol
    assertEquals(987, someObject.someFunction());
                                ^
  symbol:   method someFunction()
  location: variable someObject of type SomeInternalClassWithMembers
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:63: error: cannot find symbol
    assertEquals(765, SomeInternalClassWithMembers.someStaticFunction());
                                                  ^
  symbol:   method someStaticFunction()
  location: class SomeInternalClassWithMembers
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:68: error: cannot find symbol
    SomeInternalStructWithMembers someObject = SomeInternalStructWithMembers.create();
                                                                            ^
  symbol:   method create()
  location: class SomeInternalStructWithMembers
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:69: error: cannot find symbol
    assertEquals(123, someObject.someInteger);
                                ^
  symbol:   variable someInteger
  location: variable someObject of type SomeInternalStructWithMembers
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:70: error: cannot find symbol
    assertEquals(456, someObject.someLong);
                                ^
  symbol:   variable someLong
  location: variable someObject of type SomeInternalStructWithMembers
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:75: error: cannot find symbol
    SomeInternalStructWithMembers someObject = SomeInternalStructWithMembers.create();
                                                                            ^
  symbol:   method create()
  location: class SomeInternalStructWithMembers
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:76: error: cannot find symbol
    assertEquals(32, someObject.someFunction());
                               ^
  symbol:   method someFunction()
  location: variable someObject of type SomeInternalStructWithMembers
```

Signed-off-by: Patryk Wrobel <183546751+pwrobeldev@users.noreply.github.com>