functional-tests: do not trigger compilation error in Java/Kotlin interop test
Because we generate 'JvmSynthetic' for exception fields, the compilation error
was trigerred.

```
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:76: error: cannot find symbol
    assertEquals(exception.error, SomeInternalEnum.ONE);
                          ^
  symbol:   variable error
  location: variable exception of type SomethingBadHappenedException
```

Signed-off-by: Patryk Wrobel <183546751+pwrobeldev@users.noreply.github.com>