functional-tests: show problem with LimeEnum and JvmSuppressWildcards
The new test experiences compilation error because of missing
'JvmSuppressWildcards'.

```
gluecodium/functional-tests/functional/android/src/test/java/com/here/android/test/KotlinInteropTest.java:82:
error: incompatible types: List<CAP#1> cannot be converted to List<SomeDummyEnum>
    assertEquals(0, someJavaFunctionThatTakesListOfEnums(someStruct.enumList));
                                                                   ^
  where CAP#1 is a fresh type-variable:
    CAP#1 extends SomeDummyEnum from capture of ? extends SomeDummyEnum
```

Signed-off-by: Patryk Wrobel <183546751+pwrobeldev@users.noreply.github.com>