functional: remove interop test that fails to compile
Because of the previous change the test stopped to compile as expected.
JvmSynthetic hides the getter/setter of internal static property for interface
from Java.

```
> Task :functional:compileReleaseUnitTestJavaWithJavac FAILED
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:126: error: cannot find symbol
    assertEquals("FOO_BAR", InternalAttributeInterfaceParent.getSomeInternalProperty());
                                                            ^
  symbol:   method getSomeInternalProperty()
  location: interface InternalAttributeInterfaceParent
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:128: error: cannot find symbol
    InternalAttributeInterfaceParent.setSomeInternalProperty("abc");
                                    ^
  symbol:   method setSomeInternalProperty(String)
  location: interface InternalAttributeInterfaceParent
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:129: error: cannot find symbol
    assertEquals("abc", InternalAttributeInterfaceParent.getSomeInternalProperty());
                                                        ^
  symbol:   method getSomeInternalProperty()
  location: interface InternalAttributeInterfaceParent
```

Signed-off-by: Patryk Wrobel <183546751+pwrobeldev@users.noreply.github.com>