functional: remove kotlin-java interoperability test that fail to compile
Test cases related to usage of enum 'value' field
and aliasing enumerators are removed, because they
fail to compile with the latest changes.

```
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:69: error: cannot find symbol
    assertEquals(2, someObject.value);
                              ^
  symbol:   variable value
  location: variable someObject of type SomeInternalEnum
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:75: error: cannot find symbol
    SomeInternalEnum someObject = SomeInternalEnum.SINGLE;
                                                  ^
  symbol:   variable SINGLE
  location: class SomeInternalEnum
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:76: error: cannot find symbol
    assertEquals(1, someObject.value);
```

Signed-off-by: Patryk Wrobel <183546751+pwrobeldev@users.noreply.github.com>