functional-tests: remove java interoperability cases that fail to compile
Due to usage of jvm synthetic for functions of
internal interfaces the interoperability cases
stopped to compile -- functions in such interfaces
are not visible for Java now.

```
> Task :functional:compileReleaseUnitTestJavaWithJavac FAILED
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:34: error: method does not override or implement a method from a supertype
  @OverRide
  ^
/functional/android/src/test/java/com/here/android/test/VisibilityAttributeTest.java:39: error: method does not override or implement a method from a supertype
  @OverRide
```

Signed-off-by: Patryk Wrobel <183546751+pwrobeldev@users.noreply.github.com>